# Generated by Django 5.1.6 on 2025-02-18 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('dataset_id', models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False)),
                ('dataset_name', models.CharField(max_length=20, unique=True)),
                ('dataset_description', models.TextField(blank=True, null=True)),
                ('features_size', models.IntegerField()),
                ('targets_size', models.IntegerField()),
                ('set_size', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Dataset',
                'verbose_name_plural': 'Datasets',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.DecimalField(decimal_places=0, max_digits=6, primary_key=True, serialize=False)),
                ('pixels', models.TextField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('channels_number', models.DecimalField(decimal_places=0, max_digits=1)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('interest_id', models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False)),
                ('interest_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Interest',
                'verbose_name_plural': 'Interests',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('model_id', models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False)),
                ('model_name', models.CharField(blank=True, max_length=20, null=True)),
                ('model_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Models',
            },
        ),
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('trained_model_id', models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False)),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=4)),
                ('model_path', models.CharField(max_length=255, unique=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fer_database_app.dataset')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fer_database_app.model')),
            ],
            options={
                'verbose_name': 'Trained Model',
                'verbose_name_plural': 'Trained Models',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('interests', models.ManyToManyField(blank=True, related_name='users', to='fer_database_app.interest')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='UsageHistory',
            fields=[
                ('operation_id', models.DecimalField(decimal_places=0, max_digits=6, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('result', models.CharField(max_length=20)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fer_database_app.image')),
                ('trained_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fer_database_app.trainedmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fer_database_app.user')),
            ],
            options={
                'verbose_name': 'Usage History',
                'verbose_name_plural': 'Usage Histories',
            },
        ),
    ]
