# Generated by Django 5.1.6 on 2025-02-20 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fer_database_app', '0002_alter_usagehistory_user_usermodel_delete_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='login',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='password',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='user_model', to='fer_database_app.interest'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_model', to=settings.AUTH_USER_MODEL),
        ),
    ]
