# Generated by Django 5.1.6 on 2025-02-22 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fer_database_app', '0003_remove_usermodel_email_remove_usermodel_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='interests',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='trained_model_id',
            field=models.ForeignKey(default=1001, on_delete=django.db.models.deletion.RESTRICT, to='fer_database_app.trainedmodel'),
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
