# Generated by Django 5.1.6 on 2025-02-22 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fer_database_app', '0004_remove_usermodel_interests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='trained_model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fer_database_app.trainedmodel'),
        ),
    ]
