# Generated by Django 5.1.6 on 2025-02-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fer_database_app', '0005_alter_usermodel_trained_model_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='trained_model_id',
            new_name='trained_model',
        ),
    ]
