# Generated by Django 5.1.6 on 2025-02-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fer_database_app', '0007_remove_usermodel_users_id_alter_usermodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
