# Generated by Django 5.1.6 on 2025-02-25 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fer_database_app', '0008_alter_image_image_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagehistory',
            name='trained_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fer_database_app.trainedmodel'),
        ),
        migrations.AlterField(
            model_name='usagehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
