# Generated by Django 5.1.6 on 2025-02-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fer_database_app', '0009_alter_usagehistory_trained_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='channels_number',
        ),
        migrations.RemoveField(
            model_name='image',
            name='height',
        ),
        migrations.RemoveField(
            model_name='image',
            name='pixels',
        ),
        migrations.RemoveField(
            model_name='image',
            name='width',
        ),
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usagehistory',
            name='operation_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
