# Generated by Django 5.1.6 on 2025-02-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fer_database_app', '0010_remove_image_channels_number_remove_image_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagehistory',
            name='timestamp',
            field=models.CharField(max_length=20),
        ),
    ]
